document.writeln("<!DOCTYPE html PUBLIC \"-\/\/W3C\/\/DTD XHTML 1.0 Transitional\/\/EN\" \"http:\/\/www.w3.org\/TR\/xhtml1\/DTD\/xhtml1-transitional.dtd\">");
document.writeln("<html xmlns=\"http:\/\/www.w3.org\/1999\/xhtml\">");
document.writeln("<head>");
document.writeln("<title>浮动在网页右侧的简洁QQ在线客服<\/title>");
document.writeln("<meta http-equiv=\"content-type\" content=\"text\/html;charset=gb2312\">");
document.writeln("<style type=\"text\/css\">");
document.writeln(".qqbox a:link {");
document.writeln("	color: #000;");
document.writeln("	text-decoration: none;");
document.writeln("}");
document.writeln(".qqbox a:visited {");
document.writeln("	color: #000;");
document.writeln("	text-decoration: none;");
document.writeln("}");
document.writeln(".qqbox a:hover {");
document.writeln("	color: #f80000;");
document.writeln("	text-decoration: underline;");
document.writeln("}");
document.writeln(".qqbox a:active {");
document.writeln("	color: #f80000;");
document.writeln("	text-decoration: underline;");
document.writeln("}");
document.writeln("");
document.writeln(".qqbox{");
document.writeln("	width:132px;");
document.writeln("	height:auto;");
document.writeln("	overflow:hidden;");
document.writeln("	position:absolute;");
document.writeln("	right:0;");
document.writeln("	top:100px;");
document.writeln("	color:#000000;");
document.writeln("	font-size:12px;");
document.writeln("	letter-spacing:0px;z-index:2000");
document.writeln("}");
document.writeln(".qqlv{");
document.writeln("	width:25px;");
document.writeln("	height:256px;");
document.writeln("	overflow:hidden;");
document.writeln("	position:relative;");
document.writeln("	float:right;");
document.writeln("	z-index:50px;");
document.writeln("}");
document.writeln(".qqkf{");
document.writeln("	width:120px;");
document.writeln("	height:auto;");
document.writeln("	overflow:hidden;");
document.writeln("	right:0;");
document.writeln("	top:0;");
document.writeln("	z-index:99px;");
document.writeln("	border:6px solid #138907;");
document.writeln("	background:#fff;");
document.writeln("}");
document.writeln(".qqkfbt{");
document.writeln("	width:118px;");
document.writeln("	height:20px;");
document.writeln("	overflow:hidden;");
document.writeln("	background:#138907;");
document.writeln("	line-height:20px;");
document.writeln("	font-weight:bold;");
document.writeln("	color:#fff;");
document.writeln("	position:relative;");
document.writeln("	border:1px solid #9CD052;");
document.writeln("	cursor:pointer;");
document.writeln("	text-align:center;");
document.writeln("}");
document.writeln(".qqkfhm{");
document.writeln("	width:112px;");
document.writeln("	height:22px;");
document.writeln("	overflow:hidden;");
document.writeln("	line-height:22px;");
document.writeln("	padding-right:8px;");
document.writeln("	position:relative;");
document.writeln("	margin:3px 0;");
document.writeln("}");
document.writeln(".bgdh{");
document.writeln("	width:102px;");
document.writeln("	padding-left:10px;");
document.writeln("}");
document.writeln("<\/style>");
document.writeln("<\/head>");
document.writeln("<body>");
document.writeln("<div class=\"qqbox\" id=\"divQQbox\">");
document.writeln("  <div class=\"qqlv\" id=\"meumid\" onmouseover=\"show()\"><img src=\"images\/qqqq.gif\"><\/div>");
document.writeln("  <div class=\"qqkf\" style=\"display:none;\" id=\"contentid\" onmouseout=\"hideMsgBox(event)\">");
document.writeln("    <div class=\"qqkfbt\" onmouseout=\"showandhide(\'qq-\',\'qqkfbt\',\'qqkfbt\',\'K\',1,1);\" id=\"qq-1\" onfocus=\"this.blur();\">客 服 中 心<\/div>");
document.writeln("    <div id=\"K1\">");
document.writeln("      <div class=\"qqkfhm bgdh\"> <a href=\"http:\/\/wpa.qq.com\/msgrd?v=3&uin=859680966&site=qq&menu=yes\" title=\"前台接待\"><img src=\"http:\/\/wpa.qq.com\/pa?p=1:616591415:4\" border=\"0\">前台接待<\/a><br\/><\/div>");
document.writeln("      <div class=\"qqkfhm bgdh\"> <a href=\"http:\/\/wpa.qq.com\/msgrd?v=3&uin=859680966&site=qq&menu=yes\" title=\"充值提现\"><img src=\"http:\/\/wpa.qq.com\/pa?p=1:616591415:4\" border=\"0\">技术服务<\/a><\/div>");
document.writeln("      <div class=\"qqkfhm bgdh\"> <a href=\"http:\/\/wpa.qq.com\/msgrd?v=3&uin=859680966&site=qq&menu=yes\" title=\"投诉建议\"><img src=\"http:\/\/wpa.qq.com\/pa?p=1:616591415:4\" border=\"0\">投诉建议<\/a><\/div>");
document.writeln("     <div class=\"qqkfhm bgdh\"> <a href=\"http:\/\/wpa.qq.com\/msgrd?v=3&uin=859680966&site=qq&menu=yes\" title=\"投放广告\"><img src=\"http:\/\/wpa.qq.com\/pa?p=1:616591415:4\" border=\"0\">广告合作<\/a><\/div>");
document.writeln("    <div class=\"qqkfbt\" onmouseout=\"showandhide(\'qq-\',\'qqkfbt\',\'qqkfbt\',\'K\',1,1);\" id=\"qq-1\" onfocus=\"this.blur();\">     <\/div>");

document.writeln("    <\/div>");
document.writeln("  <\/div>");
document.writeln("<\/div>");
document.writeln("<script language=\"javascript\">");
document.writeln("function showandhide(h_id,hon_class,hout_class,c_id,totalnumber,activeno) {");
document.writeln("    var h_id,hon_id,hout_id,c_id,totalnumber,activeno;");
document.writeln("    for (var i=1;i<=totalnumber;i++) {");
document.writeln("        document.getElementById(c_id+i).style.display=\'none\';");
document.writeln("        document.getElementById(h_id+i).className=hout_class;");
document.writeln("    }");
document.writeln("    document.getElementById(c_id+activeno).style.display=\'block\';");
document.writeln("    document.getElementById(h_id+activeno).className=hon_class;");
document.writeln("}");
document.writeln("var tips; ");
document.writeln("var theTop = 40;");
document.writeln("var old = theTop;");
document.writeln("function initFloatTips() ");
document.writeln("{ ");
document.writeln("	tips = document.getElementById(\'divQQbox\');");
document.writeln("	moveTips();");
document.writeln("}");
document.writeln("function moveTips()");
document.writeln("{");
document.writeln("	 	  var tt=50; ");
document.writeln("		  if (window.innerHeight) ");
document.writeln("		  {");
document.writeln("			  pos = window.pageYOffset  ");
document.writeln("		  }else if (document.documentElement && document.documentElement.scrollTop) {");
document.writeln("			 pos = document.documentElement.scrollTop  ");
document.writeln("		  }else if (document.body) {");
document.writeln("		    pos = document.body.scrollTop;  ");
document.writeln("		  }");
document.writeln("		  pos=pos-tips.offsetTop+theTop; ");
document.writeln("		  pos=tips.offsetTop+pos\/10; ");
document.writeln("		  if (pos < theTop){");
document.writeln("			 pos = theTop;");
document.writeln("		  }");
document.writeln("		  if (pos != old) { ");
document.writeln("			 tips.style.top = pos+\"px\";");
document.writeln("			 tt=10;  \/\/alert(tips.style.top);  ");
document.writeln("		  }");
document.writeln("		  old = pos;");
document.writeln("		  setTimeout(moveTips,tt);");
document.writeln("}");
document.writeln("initFloatTips();");
document.writeln("	if(typeof(HTMLElement)!=\"undefined\")    \/\/firefox定义contains()方法，ie下不起作用");
document.writeln("		{  ");
document.writeln("		  HTMLElement.prototype.contains=function (obj)  ");
document.writeln("		  {  ");
document.writeln("			  while(obj!=null&&typeof(obj.tagName)!=\"undefind\"){");
document.writeln("	   　　 　if(obj==this) return true;  ");
document.writeln("	   　　　	　obj=obj.parentNode;");
document.writeln("	   　　	  }  ");
document.writeln("			  return false;  ");
document.writeln("		  }");
document.writeln("	}");
document.writeln("function show()");
document.writeln("{");
document.writeln("	document.getElementById(\"meumid\").style.display=\"none\"");
document.writeln("	document.getElementById(\"contentid\").style.display=\"block\"");
document.writeln("}");
document.writeln("	function hideMsgBox(theEvent){");
document.writeln("	  if (theEvent){");
document.writeln("		var browser=navigator.userAgent;");
document.writeln("		if (browser.indexOf(\"Firefox\")>0){  \/\/如果是Firefox");
document.writeln("		    if (document.getElementById(\"contentid\").contains(theEvent.relatedTarget)) {");
document.writeln("				return");
document.writeln("			}");
document.writeln("		}");
document.writeln("		if (browser.indexOf(\"MSIE\")>0 || browser.indexOf(\"Presto\")>=0){");
document.writeln("	        if (document.getElementById(\'contentid\').contains(event.toElement)) {");
document.writeln("			    return; ");
document.writeln("		    }");
document.writeln("		}");
document.writeln("	  }");
document.writeln("	  document.getElementById(\"meumid\").style.display = \"block\";");
document.writeln("	  document.getElementById(\"contentid\").style.display = \"none\";");
document.writeln(" 	}");
document.writeln("<\/script>");
document.writeln("<\/body>");
document.writeln("<\/html>")